apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base.yaml

configMapGenerator:
- name: aq-db-init
  files:
  - bootstrap.sh
- name: aq-surveys
  files:
  - demo-data/surveys/AdaptiveSimpleSurvey.json
  - demo-data/surveys/AlloyAdaptiveQuestionary.json
  - demo-data/surveys/NonAdaptiveSimpleSurvey.json
- name: aq-templates
  files:
  - demo-data/templates/adaptive.questionnaire.template.xlsx
  - demo-data/templates/adaptive.results.template.xlsx
