apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base.yaml

configMapGenerator:
- name: aq-db-init
  files:
  - bootstrap.sh
- name: aq-surveys
  files:
  - demo-data/surveys/k4s_adaptive_questionnaire_v1.0.xlsx
- name: aq-templates
  files:
  - demo-data/templates/adaptive.questionnaire.template.xlsx
  - demo-data/templates/adaptive.results.template.xlsx
