apiVersion: v1
kind: Service
metadata:
  labels:
    app: jsonagent
  name: jsonagent
spec:
  ports:
  - name: iota-north
    port: 4041
    protocol: TCP
    targetPort: 4041
  - name: iota-south
    port: 7896
    protocol: TCP
    targetPort: 7896
  selector:
    app: jsonagent

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jsonagent
  name: jsonagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsonagent
  template:
    metadata:
      labels:
        app: jsonagent
    spec:
      containers:
      - image: "fiware/iotagent-json:1.25.0"
        imagePullPolicy: IfNotPresent
        name: jsonagent
        ports:
        - containerPort: 4041
          name: iota-north
        - containerPort: 7896
          name: iota-south
        volumeMounts:
          - name: config
            mountPath: /opt/iotagent-json/config.js
            subPath: config.js
      volumes:
      - name: config
        configMap:
          name: json-agent-config
