apiVersion: v1
kind: Service
metadata:
  labels:
    app: matchmaking
  name: matchmaking
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8081
    nodePort: 8081
    targetPort: 8000
  selector:
    app: matchmaking

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matchmaking
  name: matchmaking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaking
  template:
    metadata:
      labels:
        app: matchmaking
    spec:
      containers:
        - image: "gitlab-core.supsi.ch:5050/dti-isin/omran.ayoub/matchmakingtool:0.53.0"
          imagePullPolicy: IfNotPresent
          name: matchmaking
          ports:
          - containerPort: 8000
            name: http
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-users
                key: postgres.password
          - name: "HOST1"
            value: "postgres"
          - name: "DATABASE1"
            value: "WorkerProfilerV2"
          - name: "USER1"
            value: "postgres"
          - name: "PASSWORD1"
            value: "$(POSTGRES_PASSWORD)"
          - name: "CLIENT_CSV"
            value: "/tmp/"
      volumes:
      - name: matchmaking-volume
