apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  ports:
  - port: 1883
    targetPort: mqtt
    protocol: TCP
    name: mqtt
  - port: 8080
    targetPort: ws-mqtt
    protocol: TCP
    name: ws-mqtt
  selector:
    app: mosquitto

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
  annotations:
    # Tell Reloader to bounce Mosquitto whenever the password file changes.
    secret.reloader.stakater.com/reload: "mosquitto-passwd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: "eclipse-mosquitto:2.0.15"
        imagePullPolicy: IfNotPresent
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: ws-mqtt
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: mqtt
        readinessProbe:
          tcpSocket:
            port: mqtt
        volumeMounts:
        # Mount config where the Docker image expects it to be.
        # See:
        # - https://github.com/eclipse/mosquitto/tree/master/docker/2.0
        - name: mosquitto-config
          mountPath: /mosquitto/config
        # Mount persistent storage on the volume the Docker image defines.
        # See:
        # - https://github.com/eclipse/mosquitto/tree/master/docker/2.0
        - name: mosquitto-volume
          mountPath: /mosquitto/data
        # Mount password file to match path specified in config.
        # NOTE. Path name. Our config file points to `/etc/mosquitto/passwd`
        # and the secret comes w/ a key called `passwd`. So we mount on
        # `/etc/mosquitto`.
        - name: mosquitto-passwd
          mountPath: /etc/mosquitto
          readOnly: true
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-volume
        persistentVolumeClaim:
          claimName: mosquitto-pvc
      - name: mosquitto-passwd
        secret:
          secretName: mosquitto-passwd
