#
# Plain K8s Secret template to generate the actual SealedSecret to be
# instantiated in the cluster. To generate the SealedSecret, first put
# the content of your Mosquitto password file in the `passwd` key below,
# then run
#
#   $ kubeseal -o yaml < templates/mosquitto-passwd.yaml > mosquitto-passwd.yaml
#
# Notice `kubeseal` needs to be able to access the cluster for that to
# work. You can also work offline if you like, but you'll have to fetch
# the controller pub key with `kubeseal --fetch-cert` beforehand. Read
# the docs for the details.
#
# WARNING. **Never** commit this file to the repo with an actual
# password in it. After editing this file, just ask git to ditch
# the local changes.
#
# NOTE. Mosquitto password file.
# As already mentioned, the value of the `passwd` key are the lines
# that make up the Mosquitto password file you want to deploy. One
# easy way to manage the content is to use `mosquitto_passwd` to generate
# each line you want to keep in here, so you won't ever need a separate
# Mosquitto password file. For example, say you'd like to add a user
# "bot42". The following command asks you for a password and then prints
# the line you'd have to add to `passwd`:
#
#   $ mosquitto_passwd -c /dev/stdout bot42
#
# Likewise, if you wanted to change the password of an existing user,
# say the "iot" user, you'd run the above command again with "iot"
# instead of "bot42" and then replace the "iot:..." line in `passwd`
# with the line the command printed.
#
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  namespace: default
  annotations:
    # Let Sealed Secrets Controller update this Secret whenever the
    # corresponding SealedSecret changes. When we update a SealedSecret,
    # Controller will extract its Secret, but if the old Secret currently
    # live in K8s doesn't have this annotation, Controller will refuse to
    # update it with the new content just unsealed.
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
  passwd: |
    iot:$7$101$LxdahvM20GlxG7En$NRB+nEltMdLALJEgv/ik4w/YomeLXCadY2N8IrjrI6RhRQLxo/Bot2F2b2OFIUoJ3bvRAeG8SBycGvYzUZGttA==
