apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fams-image
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA29Tz80MOFzf9dYIRiKDT8KVLX71/Wo/2+lYJWjPBVpQ6avwQRjVKmADFKiqXKuO5TKBiDYYsowXVqjjlSnwhjztlnEZWcsTs7zniVl6Dr1Jjs1TTLGnzxIKDDWaeGEFvyTJdrOeBI6uWr/d85rewOD3eGGdK8yaiFZHiBjk5qoNv+y+EVz3R2p8vrLQsG3GhMDJBfQ+GIE+2o2owok/IN9EBzMSva1El3RHT4zhJxhOaCDeMsopoTwZUkPjJWXieX6WzUDY0RAm3trBOo5yltL5yL8NoQ+52C7If9UQ55HN8J3u1VBivjEYwnW5g1GOSFULnJiMa/gAMRMOA88EUqXRYQNJ4plmDADSOabLu+0mw8jo/I6pnhgOEMmu27fw52z3/umkpuvq9PIjQr+3ZvmZXDSRkNGidTeT4X0kP+teMwhoTIjqjF4RZTKpcfMPZT4i+nH4B1ZtLNZrUQThVvbbh5AUWxmtUsIBB12ML9dZLhUprkTt8SiQM/1Tgumt9X7BfvalNJWF897wxGW09TV4PnQ6jhNWBpktLAul+S4gzP1tJ2HAjwJhWZxRTcrD/jh2RLzg2b1QxWDRsWjCB7W1kkS8ao+BQx0wGntObM/QSGDBqzsoHUzdbm5PqEnjRt09J4HbBb34JG2UmDZPY+6eIKMNXjTrrlzL6B9ORUZftafKn+8VmO+HhEobP1WeO47oaVLTfCT7imJ2+QnbxMqJKgL0xNQ5O3bUC0npQq0hp9g6Ywxt3cy80WIhS97R3aYHiwBNqT64R5yXL0gjQHIAKjZ3t9WScQ7JYXPzGRUAbGw0gvMMZcXl/annetlciA30VTKxux+CZj2SRwHekPE8+xrOmredmN2kbAcjs+nfYmFcPI8Z+fJnhbfD1sYygHnc1SadZKVJbTqrj1qU3EJangHLk3kQKQZpK5mrobY8hJyiCnrY3oGVzl/0b9sE7kOAr+RO+Vhf3ISQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: fams-image
      namespace: default
    type: kubernetes.io/dockerconfigjson

