apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: insight-image
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAjDAZ2PpWPHSia2ZZoofN0ylLLICKbY/0Knt5V7s8qqzRj88RtugAlrq5OZAjwiRNqa5G0gVU8UiONNrAvzdlmZsjvfNEhsjTiE5HVYS9iRDqg9GPzSlaotxoGi1wLSPzmG1tw+X2sDUmS94EDoxeDe6gyN6TeYG3UikpWYTmztxuqdNwrKCsx0W8NVVDNIX3lMdHQkZ8syr3EwApQQVmSp/4vl3j5RQ9JYSeiUI2cZUD6+LvUxH4uEnxwC0NST4p2VGHBV3oWRynvLiOzsNrSVPJ69NMiAL//T4+0Ln1lUXl6UK1JBvsZ0sh8LORgqJbON0ogtUDX6eQP3yv75WdFBN4v87dtkJOLOUaqup07KZv7+ffU2XvXoEspSYMJDGzn19LXOdJbP/5csqr4SQyCxSGLsDjxV3LB0ZVgInbZDbHAwrwTEv/Dkkxaj9cgqbKLvMdFh5yvZ/T0S8fSxEiJkXz6870mNoVQ4n+VC5x3wbm1CeNrohgfuKihR6y0OXqLvQoWDKqzrFW4K5NchFP21I2yrTgws73sPspSL+zPG13Tcs/fupH6cwqFsSdwJ1DYdO1R+T9TNIy9pPWLmHCDwidPdrsizVq4D7fwU3kdxz/yIEXDEld7eLNQXfIdrI6QJoVh9kFeTTtbzy2IncQTR23tdP9dIs9PG/+nIKPkySnP4LxFX7YpHQ+iW0UzAGarVAPyNs1rs8ooVeNh+dSymhASWZDKgvGNFqSkEyX5WgUq+/VBgDXMXU6REdO14CzJpyoOqiNKHz5I+Lw5rAFdRTUiyKaXY/EKSL2cOSTtO37q7MgH/+ZOOVBMaddU3YeqdCsSd2G+VtvQgpUwtQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: insight-image
      namespace: default
    type: kubernetes.io/dockerconfigjson

