apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgCGR7YwBKy42WsGj0lkKme06mQEoDq5IQaaxh7P1m+qmknW2L6GiHMA2yr53pkLomFhfCY7AKHxyMSehH89vISnggkSkX3mfEf9FSXl+YkEg5qM3NtTNn5jpx9Tx0orSJ77a9zGu9w45NSs8sFa+58ubPT+65L77Uu9bi1pTLCCc8cXXWqYBlmmmPAkS3iKs5f49v1Yox8uf44BGg2XXzIxgxp6y6Xsf+hGLm7tn8OtNg/gUc2b+uY3a/fTteXpznPmWZ0j5bVEc0pDQnC3Bptrnguhz5O9RM0lVHEB8WPFRVor5F/ts9yJqFwf4UnXWRQ7qEoh2k/Mt6OQS9lszgU7aoYa8MkbCrFdY4bu54yKoHeYaxue6/hFOkpkE4UiBDvSg6d/IakEF8HxLjfFoOIpRqWFEHBh+AU6ny9+1m8V1eHyJPJn6swC8KIuOht9NUqFVHLXakqEFmioi1uhFwXz3ZlbptbqS5yYrl3G/wAtjeZy+VqYCelLRi+ToFgE1DBUQ8snBPanVZcJOEVKwgfV93ifzKUOij4xyZbwFZk/bXPkM15/gkx29py4Oo8hD1X+5g2HSDtDgxw9nK4JShNbo1i5CMLaDDop32uIsTySCYz3mGOiKjLaMpLRRKJ4XRCkxazCPRpnmwy1HN+Dgqs3D9kqDGcQs9TCC0/M/zV+4WbNv3Jtk4YjQPvpQCzlarRJA7leiQ9Ba6ECmnqvBH+FqC1M4EYyJj8L9ETpSpb0S5H3QWWLb/wK7pT6vbSvG1QU2EFA5b3dk2MTclJKKZPLM4W9DSgp7kM+zdba++omVJLUtsr8VCVyDHR8RbNsLBKllqhImSL0IseRWR2CgTKUPhgM8c0=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: mosquitto-passwd
      namespace: default
    type: Opaque

